### ISSUE TITLE
Is there a way to use the `MKFS_PARM` struct?

### ISSUE THREAD

**Issue by acheronfail** [irori/js-fatfs#3]
I'm trying to use `f_mkfs` as documented here: http://elm-chan.org/fsw/ff/doc/mkfs.html

I need to set some specific options with `MKFS_PARM` (namely the `fmt`, `n_fat` and `au_size` fields). As far as I can tell, `fs-fatfs` doesn't expose the `MKFS_PARM` struct? It does expose the [`f_mkfs` function](https://github.com/irori/js-fatfs/blob/main/dist/fatfs.d.ts#L32) though.

**Comment by blitzbrian** [comment]
I got it half working using this:
```ts
function makeFileSystem(ff: FatFsTypes.FatFs) {
    const work = ff.malloc(FatFs.FF_MAX_SS);

    const fmt = (FatFs.FM_SFD | FatFs.FM_ANY) & 0xff;
    const n_fat = (1 & 0xff) << 8;
    const align = (0 & 0xffff) << 16;
    const n_root = (0 & 0xffff) << 32;
    const au_size = (0 & 0xffffffff) << 48;

    const flags = ff.malloc(8);

    console.log(fmt | n_fat | align | n_root | au_size);

    ff.setValue(flags, fmt | n_fat | align | n_root | au_size, "*");

    ff.f_mkfs("", flags, work, FatFs.FF_MAX_SS);
    ff.free(work);
}
```

**Comment by irori** [comment]
In v0.2.0, `f_mkfs()` accepts `opt` parameter of type [MkfsParams](https://github.com/irori/js-fatfs/blob/v0.2.0/dist/fatfs.d.ts#L75-L81), like this:

```javascript
	const ff = await FatFs.create({ ... });
	const opts = { fmt: FatFs.FM_FAT, n_fat: 1, align: 0, n_root: 0, au_size: 4096 };
	ff.f_mkfs('', opts, work, FatFs.FF_MAX_SS);
```

**Comment by acheronfail** [comment]
Absolutely phenomenal work @irori thank you so much!
